[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "django-customer-billing>=1.7.24",
    "reportlab>=4.4.1",
    "streamlit>=1.45.1",
]
